<a href="https://colab.research.google.com/github/AnnaShtyn/python_for_hw_tasks/blob/main/Anna_Shtyn_HW_16_1_%D0%9F%D1%80%D0%BE%D0%B3%D0%BD%D0%BE%D0%B7%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_%D0%BE%D1%80%D0%B5%D0%BD%D0%B4%D0%BD%D0%BE%D1%97_%D0%BF%D0%BB%D0%B0%D1%82%D0%B8_%D0%B7%D0%B0_%D0%B6%D0%B8%D1%82%D0%BB%D0%BE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнє завдання: Прогнозування орендної плати за житло

## Мета завдання
Застосувати знання з лекції для побудови моделі лінійної регресії, що прогнозує орендну плату за житло в Індії. Ви пройдете весь цикл вирішення задачі машинного навчання: від дослідницького аналізу до оцінки якості моделі.

## Опис датасету
**House Rent Prediction Dataset** містить інформацію про 4700+ оголошень про оренду житла в Індії з такими параметрами:
- **BHK**: Кількість спалень, залів, кухонь
- **Rent**: Орендна плата (цільова змінна)
- **Size**: Площа в квадратних футах
- **Floor**: Поверх та загальна кількість поверхів
- **Area Type**: Тип розрахунку площі
- **Area Locality**: Район
- **City**: Місто
- **Furnishing Status**: Стан меблювання
- **Tenant Preferred**: Тип орендаря
- **Bathroom**: Кількість ванних кімнат
- **Point of Contact**: Контактна особа

---

## Завдання 1: Завантаження та перший огляд даних (1 бал)

**Що потрібно зробити:**
1. Завантажте дані з файлу `House_Rent_Dataset.csv`
2. Виведіть розмір датасету
3. Покажіть перші 5 рядків
4. Виведіть загальну інформацію про дані (включно з типами даних та кількістю значень)

In [50]:
import pandas as pd
import numpy as np

df = pd.read_csv('drive/MyDrive/House_Rent_Dataset.csv')
df.shape

(4746, 12)

In [51]:
df.head(5)

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   object
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Floor              4746 non-null   object
 5   Area Type          4746 non-null   object
 6   Area Locality      4746 non-null   object
 7   City               4746 non-null   object
 8   Furnishing Status  4746 non-null   object
 9   Tenant Preferred   4746 non-null   object
 10  Bathroom           4746 non-null   int64
 11  Point of Contact   4746 non-null   object
dtypes: int64(4), object(8)
memory usage: 445.1+ KB

## Завдання 2: Дослідницький аналіз даних (EDA) (5 балів)

**Що потрібно зробити:**
1. **Аналіз пропущених значень.** Перевірте наявність і відсоток пропущених значень у кожній колонці
2. **Базова статистика.** Обчисліть базову статистику (середнє, квартилі, стандартне відхилення) для числових змінних.
3. **Аналіз цільової змінної.** Побудуйте гістограму розподілу цільової змінної (Rent)
4. **Робота з викидами.** Знайдіть та видаліть викиди в цільовій змінній (якщо є). Визначити викиди можна будь-яким зрозумілим для вас способом, як варіант - таким, що використовується в побудові box-plot (https://en.wikipedia.org/wiki/Box_plot#Example_with_outliers).
5. **Аналіз категоріальних змінних.** Виведіть кількість унікальних значень для кожної з категоріальних колонок.

In [53]:
# 2.1.
miss_data = df.isnull().sum()
miss_perc = (miss_data/len(df)) * 100
print(miss_data, miss_perc)
# пропущені дані відсутні

Posted On            0
BHK                  0
Rent                 0
Size                 0
Floor                0
Area Type            0
Area Locality        0
City                 0
Furnishing Status    0
Tenant Preferred     0
Bathroom             0
Point of Contact     0
dtype: int64 Posted On            0.0
BHK                  0.0
Rent                 0.0
Size                 0.0
Floor                0.0
Area Type            0.0
Area Locality        0.0
City                 0.0
Furnishing Status    0.0
Tenant Preferred     0.0
Bathroom             0.0
Point of Contact     0.0
dtype: float64

In [54]:
# 2.2.
df.describe().round(2)

           BHK        Rent     Size  Bathroom
count  4746.00     4746.00  4746.00   4746.00
mean      2.08    34993.45   967.49      1.97
std       0.83    78106.41   634.20      0.88
min       1.00     1200.00    10.00      1.00
25%       2.00    10000.00   550.00      1.00
50%       2.00    16000.00   850.00      2.00
75%       3.00    33000.00  1200.00      2.00
max       6.00  3500000.00  8000.00     10.00

In [55]:
# 2.3.
import plotly.express as px

fig = px.histogram(
    df,
    x='Rent',
    nbins = 100,
    title='Розподіл цільової змінної (орендна плата)',
    labels={'Rent':'Орендна плата', 'count':'К-сть оголошень'}
)
fig.show()

In [56]:
# 2.4.
fig = px.box(df, y='Rent', labels={'Rent':'Орендна плата'}, title='Аналіз викидів цільової змінної(орендної плати)')
fig.show()

#  Отже, згідно побудованого "ящика з  вусами", 'викиди' орендної плати у нас -
# починаючи від 67тис. у.о. Також, оскільки в нас пораховані квартилі, можна
# розрахувати 'викиди' на їхній основі :
#  міжкварт. розмах = 33000 - 10000 = 23000
#  нижня межа 'викидів' = 10000 - 1,5*23000 = -24500 (немає мінусових значень)
#  верхня межа 'викидів' = 33000 + 1,5*23000 = 67500
#  Таким чином, у нас 'викиди' починаючи від 67500 у.о.

In [57]:
# 2.4. Усунемо викиди в даних орендної плати:
df_clean = df[df['Rent'] < 67500]
df_clean.shape
# Як бачимо, 500+ записів відсіялось

(4226, 12)

In [58]:
df_clean.head(2)

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner

In [59]:
# 2.5.
print(f'Унікальні значення категоріальних колонок\nFloor: {df_clean['Floor'].nunique()}\nArea Type: {df_clean['Area Type'].nunique()}\nArea Locality: {df_clean['Area Locality'].nunique()}\nCity: {df_clean['City'].nunique()}\nFurnishing Status: {df_clean['Furnishing Status'].nunique()}\nTenant Preferred: {df_clean['Tenant Preferred'].nunique()}\nPoint of Contact: {df_clean['Point of Contact'].nunique()}')

Унікальні значення категоріальних колонок
Floor: 340
Area Type: 3
Area Locality: 1997
City: 6
Furnishing Status: 3
Tenant Preferred: 3
Point of Contact: 3


## Завдання 3: Аналіз кореляцій та взаємозв'язків (3 бали)

**Що потрібно зробити:**
1. Обчисліть матрицю кореляцій для числових змінних
2. Візуалізуйте кореляційну матрицю за допомогою heatmap
3. Побудуйте scatter plot між Size та Rent
4. Проаналізуйте взаємозв'язок між BHK та Rent за допомогою boxplot (який розподіл плати для різних значень BHK)

In [60]:
# 1,2
corr_matr = df_clean.select_dtypes('number').corr()
pd.DataFrame(corr_matr).style.background_gradient(cmap='Reds')

In [61]:
# 3.
px.scatter(df_clean,
           x='Size',
           y='Rent',
           labels={'Size' : 'Площа житла', 'Rent' : 'Оренд. плата'},
           title="Взаємозв'язок між площею житла та орендною платою")
# Вочевидь, оскільки коеф. кореляції 0.39, однозначного тренду не видно.

In [62]:
# 4.
px.box(df_clean,
       x='BHK',
       y='Rent',
       labels={'BHK' : 'К-сть кімнат', 'Rent':'Орендна плата'},
       title='Розкид величини оренд.плати залежно від кількості кімнат житла')
# Найбільший розкид бачимо для 1,2,3 -кімнатного житла

## Завдання 4: Feature Engineering та підготовка даних (4 бали)

**Що потрібно зробити:**
1. Закодуйте категоріальні змінні за допомогою One-Hot Encoding. Пригадайте, що в лекції ми говорили щодо кодування кат. змінних з великої кількістю різних значень і як працювати з такими випадками. Ви можете закодувати не всі кат. змінні, а лише ті, що вважаєте за потрібні (скажімо ті, що мають відносно небагато різних значень).
2. **Опціонально (по 0.5 бала за кожну доцільну ознаку):** Додайте нові ознаки, обчислені на основі наявних даних, які б на ваш погляд були корисними для моделі
3. Виберіть ознаки для побудови моделі (виключіть непотрібні колонки). Виключити можна, наприклад, ті колонки, які мають категоріальний тип і забагато (більше 20) різних значень. Треба виключити хоча б 1 колонку.
4. Розділіть дані на ознаки (X) та цільову змінну (y)
5. Застосуйте стандартизацію до числових ознак

In [63]:
# 1. Не будемо кодувати стовпці 'Floor' та 'Area Locality' оскільки там забагато
#    значень, і модель не зможе знайти патерни.

area_type_dummies = pd.get_dummies(df_clean['Area Type'], prefix='area_type').astype(int)
city_dummies = pd.get_dummies(df_clean['City'], prefix='city').astype(int)
furnishing_dummies = pd.get_dummies(df_clean['Furnishing Status'], prefix='furnishing').astype(int)
tenant_dummies = pd.get_dummies(df_clean['Tenant Preferred'], prefix='tenant').astype(int)
contact_dummies = pd.get_dummies(df_clean['Point of Contact'], prefix='contact').astype(int)

In [85]:
# 3. додамо нові закодовані колонки до датафрейму

df_clean_new = pd.concat([df_clean, area_type_dummies, city_dummies, furnishing_dummies, tenant_dummies, contact_dummies], axis=1)

#  та видалимо зайві (текстові), і перевіримо остаточні колонки нового датафрейму
df_clean_new = df_clean_new.drop(['Floor', 'Area Locality', 'Posted On', 'Area Type', 'City', 'Furnishing Status', 'Tenant Preferred', 'Point of Contact'], axis=1)
df_clean_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4226 entries, 0 to 4745
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   BHK                        4226 non-null   int64
 1   Rent                       4226 non-null   int64
 2   Size                       4226 non-null   int64
 3   Bathroom                   4226 non-null   int64
 4   area_type_Built Area       4226 non-null   int64
 5   area_type_Carpet Area      4226 non-null   int64
 6   area_type_Super Area       4226 non-null   int64
 7   city_Bangalore             4226 non-null   int64
 8   city_Chennai               4226 non-null   int64
 9   city_Delhi                 4226 non-null   int64
 10  city_Hyderabad             4226 non-null   int64
 11  city_Kolkata               4226 non-null   int64
 12  city_Mumbai                4226 non-null   int64
 13  furnishing_Furnished       4226 non-null   int64
 14  furnishing_Semi-Furnished  4226 non-null   int64
 15  furnishing_Unfurnished     4226 non-null   int64
 16  tenant_Bachelors           4226 non-null   int64
 17  tenant_Bachelors/Family    4226 non-null   int64
 18  tenant_Family              4226 non-null   int64
 19  contact_Contact Agent      4226 non-null   int64
 20  contact_Contact Builder    4226 non-null   int64
 21  contact_Contact Owner      4226 non-null   int64
dtypes: int64(22)
memory usage: 888.4 KB

In [86]:
# 4. Отже, оскільки в нас оригінальні числові ознаки досить суттєві (згідно з кор.)
#   матрицею), ми беремо їх та закодовані категоріальні ознаки (тобто всі ознаки з
#   df_clean_new окрім цільової 'Rent')

x = df_clean_new.drop(['Rent'], axis=1)
y = df_clean_new['Rent']
print(x.shape, y.shape)

(4226, 21) (4226,)

In [88]:
# 5.
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled_df = pd.DataFrame(x_scaled, columns=x.columns, index=x.index)
x_scaled_df.head()

,BHK,Size,Bathroom,area_type_Built Area,area_type_Carpet Area,area_type_Super Area,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,...,city_Mumbai,furnishing_Furnished,furnishing_Semi-Furnished,furnishing_Unfurnished,tenant_Bachelors,tenant_Bachelors/Family,tenant_Family,contact_Contact Agent,contact_Contact Builder,contact_Contact Owner
0,0.052966,0.469859,0.272578,-0.02176,-0.878583,0.879429,-0.502144,-0.501774,-0.387614,-0.499926,...,-0.408755,-0.374584,-0.940704,1.205870,-0.456579,0.597576,-0.315692,-0.577532,-0.015385,0.577897
1,0.052966,-0.147778,-1.133910,-0.02176,-0.878583,0.879429,-0.502144,-0.501774,-0.387614,-0.499926,...,-0.408755,-0.374584,1.063034,-0.829277,-0.456579,0.597576,-0.315692,-0.577532,-0.015385,0.577897
2,0.052966,0.263980,-1.133910,-0.02176,-0.878583,0.879429,-0.502144,-0.501774,-0.387614,-0.499926,...,-0.408755,-0.374584,1.063034,-0.829277,-0.456579,0.597576,-0.315692,-0.577532,-0.015385,0.577897
3,0.052966,-0.147778,-1.133910,-0.02176,-0.878583,0.879429,-0.502144,-0.501774,-0.387614,-0.499926,...,-0.408755,-0.374584,-0.940704,1.205870,-0.456579,0.597576,-0.315692,-0.577532,-0.015385,0.577897
4,0.052966,-0.044839,-1.133910,-0.02176,1.138197,-1.137102,-0.502144,-0.501774,-0.387614,-0.499926,...,-0.408755,-0.374584,-0.940704,1.205870,2.190201,-1.673428,-0.315692,-0.577532,-0.015385,0.577897

## Завдання 5: Розділення даних та навчання моделі (3 бали)

**Що потрібно зробити:**
1. Розділіть дані на навчальну (80%) та тестову (20%) вибірки.
2. Створіть модель лінійної регресії.
3. Навчіть модель на навчальних даних.
4. Виведіть усі коефіцієнти моделі (ваги) та напишіть, які 2 ознаки найбільше впливають на прогноз.
5. Зробіть прогнози на тренувальній та тестовій вибірках.

In [89]:
# 1.
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x_scaled_df, y, test_size=0.2, random_state=10
)

In [93]:
# 2,3.
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [151]:
# 4.
for feature, weight in zip(model.feature_names_in_, model.coef_):
    print(f'{feature}: {weight:.2f}')

print(f'Незалежний параметр (intercept): {model.intercept_:.2f}')

coef_imp = pd.Series(model.coef_, index=x.columns).sort_values(key=np.abs, ascending=False).round(2)
print(f'\nТоп-2 найвагоміших коефіцієнтів ознак\n{coef_imp.head(2)}')

BHK: 2625.14
Size: 3587.96
Bathroom: 2279.71
area_type_Built Area: -21.76
area_type_Carpet Area: 111.87
area_type_Super Area: -110.91
city_Bangalore: -785.35
city_Chennai: -1260.35
city_Delhi: 169.76
city_Hyderabad: -1687.53
city_Kolkata: -1759.68
city_Mumbai: 5760.02
furnishing_Furnished: 1109.58
furnishing_Semi-Furnished: -111.52
furnishing_Unfurnished: -628.52
tenant_Bachelors: 263.52
tenant_Bachelors/Family: 58.00
tenant_Family: -435.77
contact_Contact Agent: 1876.39
contact_Contact Builder: -19.86
contact_Contact Owner: -1875.09
Незалежний параметр (intercept): 19399.42

Топ-2 найвагоміших коефіцієнтів ознак
city_Mumbai    5760.02
Size           3587.96
dtype: float64

In [99]:
# 5.
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

comp = pd.DataFrame({
    'Реальна оренд.плата' : y_test.values[:10],
    'Прогнозована оренд.плата' : y_test_pred[:10].round(0),
    'Похибка' : y_test.values[:10] - y_test_pred[:10].round(0)
})
print(f'Приклад прогнозування на тестовій вибірці:\n{comp}')

Приклад прогнозування на тестовій вибірці:
   Реальна оренд.плата  Прогнозована оренд.плата  Похибка
0                42000                   31322.0  10678.0
1                38000                   31534.0   6466.0
2                10000                   20763.0 -10763.0
3                 6500                    3941.0   2559.0
4                15000                   18863.0  -3863.0
5                20000                   19402.0    598.0
6                 8000                    7679.0    321.0
7                15500                   12566.0   2934.0
8                13000                   13251.0   -251.0
9                16000                   19229.0  -3229.0

## Завдання 6: Оцінка якості моделі (2 бали)

**Що потрібно зробити:**
1. Обчисліть MAE, RMSE та R² для навчальної та тестової вибірок
2. Порівняйте метрики та зробіть висновок про якість моделі
3. Проаналізуйте і дайте висновок, чи є ознаки перенавчання або недонавчання (**Нагадування**: перенавчання - коли модель дуже добре працює на тренувальних даних, але погано на тестових; недонавчання - коли модель погано працює навіть на тренувальних даних)
4. Побудуйте графік розсіювання "реальні vs прогнозовані значення" та зробіть висновок про якість моделі

In [108]:
# 1,2.
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

MAE = mean_absolute_error(y_test, y_test_pred)
MSE = mean_squared_error(y_test, y_test_pred)
RMSE = np.sqrt(MSE)
R2 = r2_score(y_test, y_test_pred)
print(f'Показники якості моделі на ТЕСТОВІЙ вибірці:\nMAE: {MAE:.2f}\nMSE: {MSE:.2f}\nRMSE: {RMSE:.2f}\nR²:{R2:.2f}')

MAE_tr = mean_absolute_error(y_train, y_train_pred)
MSE_tr = mean_squared_error(y_train, y_train_pred)
RMSE_tr = np.sqrt(MSE_tr)
R2_tr = r2_score(y_train, y_train_pred)
print(f'\nПоказники якості моделі на ТРЕНУВАЛЬНІЙ вибірці:\nMAE: {MAE_tr:.2f}\nMSE: {MSE_tr:.2f}\nRMSE: {RMSE_tr:.2f}\nR²:{R2_tr:.2f}')

Показники якості моделі на ТЕСТОВІЙ вибірці:
MAE: 5764.34
MSE: 64046092.70
RMSE: 8002.88
R²:0.67

Показники якості моделі на ТРЕНУВАЛЬНІЙ вибірці:
MAE: 5515.12
MSE: 58291107.15
RMSE: 7634.86
R²:0.69

*3. Порівнявши метрики на тестовій та тренувальній вибірці можемо зазначити досить хорошу якість прогнозування (коеф-ти детермінації 0,67 та 0,69 відповідно). Між ними невелика різниця, очевидного пере-/недонавчання моделі немає. Середня абсолютна помилка в прогнозі орендної плати становить всередньому  16% (MAE / середню ор.плату).*

In [119]:
# 4.
import plotly.graph_objects as go

fig = px.scatter(
    x=y_test,
    y=y_test_pred,
    title = 'Реальна vs Прогнозована орендна плата (тестова вибірка)',
    labels={'x' : 'Реальна ор. плата', 'y' : 'Прогнозована ор. плата'},
    opacity=0.6
)
max_val = max(y_test.max(), y_test_pred.max())
fig.add_trace(
    go.Scatter(
        x=[0, max_val],
        y=[0, max_val],
        mode='lines',
        name='Ідеальний прогноз',
        line=dict(color='green')
    )
)
fig.show()

# Вочевидь з графіка модель більше схильна завищувати прогнозовану орендну плату
#  до 40 тис., та занижувати після 40 тис.

## Завдання 7: Аналіз помилок (4 бали)

**Що потрібно зробити:**
1. Обчисліть помилки (residuals = реальні - прогнозовані значення)
2. Побудуйте гістограму розподілу помилок
3. Створіть scatter plot помилок відносно величини прогнозованих значень. Чи росте помилка з ростом прогнозованого значення?
4. Знайдіть 5 прогнозів з найбільшими помилками
5. Проаналізуйте, на яких типах житла модель помиляється найбільше. Типи можна розрізняти за кількістю кімнат чи містом, наприклад.
6. Подумайте і напишіть, які наступні кроки ви б зробили, аби поліпшити якість моделі. Опціонально можна їх зробити і ми перевіримо :)

In [141]:
# 1,2.
resid = y_test - y_test_pred

fig = px.histogram(
    x=resid,
    nbins=50,
    title='Розподіл помилок прогнозування орендної плати',
    labels={'x' : 'Помилки (реал-прогноз)', 'count' : 'Кількість'}
)
fig.add_vline(x=0, line_dash='dash', line_color='red', annotation_text='Ідеальний прогноз')
fig.show()

In [142]:
# 3.
fig= px.scatter(
    x=y_test_pred,
    y=resid,
    title='Залежність помилок від прогнозованих значень орендної плати',
    labels={'x' : 'Прогнозована ор.плата', 'y' : 'Помилка'},
    opacity=0.5
)
fig.add_hline(y=0, line_dash='dash', line_color='black', annotation_text='Відсутність помилки')
fig.show()

# Так, з ростом прогнозованого значення ор. плати похибка збільшується в обидві сторони.

In [145]:
# 4.
errors_df = pd.DataFrame({
'real' : y_test.values,
'pred' : y_test_pred.round(2),
'error' : np.abs(resid).round(2)
})

top5_errors = errors_df.nlargest(5, 'error')
print(f'Топ-5 прогнозованих орендних плат з найбільшими помилками\n {top5_errors}')

Топ-5 прогнозованих орендних плат з найбільшими помилками
        real      pred     error
3912  60000  26571.64  33428.36
4076   1200  33576.90  32376.90
4696  30000  62007.16  32007.16
1150   8000  38961.21  30961.21
904    8000  38421.97  30421.97

In [171]:
# 5. Створимо таблицю абсолютних значень топ5 найбільш помилкових прогнозів, де
#   наочно бачимо 'вагу' кожної ознаки на передбачення орендної плати.

df_top5_errors_fin = x_scaled_df.loc[top5_errors.index]
df_weights = coef_imp.to_frame().T[df_top5_errors_fin.columns]

df_top5_errors_fin = df_top5_errors_fin.mul(coef_imp, axis=1).round(2).transpose()
top5_errors_fin_tot = df_top5_errors_fin.sum(axis=0)
df_top5_errors_fin.loc['Total+intercept'] = (top5_errors_fin_tot + 19399.42).round(0)

display(df_top5_errors_fin)

# Отож, для позиції 3912 прогнозоване значення набагато нижче ймовірно тому, що
#   реальна орендна плата в оголошенні була безпідставно завищена.
#  Для решти 4 оголошень прогнозована ціна значно вища через незалежний параметр
# (19499), к-сть кімнат, розмір, к-сть ванних кімнат,контактної особи та локації
#  в Мумбаї (в кожному випадку різний набір факторів).

                               3912      4076      4696      1150      904
BHK                         3657.58   3657.58  14213.17    139.04    139.04
Bathroom                    3827.78   3827.78  10240.55    621.40    621.40
Size                        6117.95   9072.70  24585.10  -1837.70  -2376.94
area_type_Built Area           0.47      0.47      0.47      0.47      0.47
area_type_Carpet Area        -98.29    127.33    -98.29    127.33    127.33
area_type_Super Area         -97.54    126.12    -97.54    126.12    126.12
city_Bangalore               394.36    394.36    394.36    394.36    394.36
city_Chennai                 632.41    632.41    632.41    632.41    632.41
city_Delhi                   -65.80    -65.80    -65.80    -65.80    -65.80
city_Hyderabad             -3375.56  -3375.56  -3375.56    843.64    843.64
city_Kolkata                 661.31    661.31    661.31    661.31    661.31
city_Mumbai                -2354.44  -2354.44  -2354.44  14091.61  14091.61
contact_Contact Agent      -1083.68  -1083.68  -1083.68   3248.98   3248.98
contact_Contact Builder        0.31      0.31      0.31      0.31      0.31
contact_Contact Owner      -1083.61  -1083.61  -1083.61   3244.68   3244.68
furnishing_Furnished        -415.63   2962.17   -415.63   -415.63   -415.63
furnishing_Semi-Furnished   -118.55    104.91   -118.55    104.91    104.91
furnishing_Unfurnished       521.22    521.22    521.22   -757.91   -757.91
tenant_Bachelors            -120.32   -120.32   -120.32   -120.32   -120.32
tenant_Bachelors/Family       34.66     34.66     34.66    -97.06    -97.06
tenant_Family                137.57    137.57    137.57  -1380.36  -1380.36
Total+intercept            26572.00  33577.00  62007.00  38961.00  38422.00

 6. *Для коректнішого передбачення можливо необхідно взяти масивнішу вибірку або поміняти тип моделі передбачення, якщо якість прогнозування не покращиться.*